apiVersion: v1
kind: Service
metadata:
  name: "gitfocus-service"
  namespace: "gitfocus-ns"
spec:
  ports:
    - port: 4041
      targetPort: 4041
      protocol: TCP
  type: NodePort
  selector:
    app: "gitfocus"