apiVersion: apps/v1
kind: Deployment
metadata:
  name: "gitfocus-alb-ingress-deployment"
  namespace: "gitfocus-ns1"
spec:
  selector:
    matchLabels:
      app: "gitfocus"
  replicas: 3
  template:
    metadata:
      labels:
        app: "gitfocus"
    spec:
      containers:
      - image: psmsenthilkumar/gitfocus-alb-ingress
        imagePullPolicy: Always
        name: "gitfocus-alb-ingress-container"
        ports:
        - containerPort: 4041